export const en = {
  common: {
    loading: 'Loading...',
    noData: 'No data',
    words: 'Words',
    chars: 'Characters',
    untitled: 'Untitled',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    confirm: 'Confirm',
    description: 'Description',
    genre: 'Genre',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
  },
  navigation: {
    libraryTitle: 'Library',
    bookDetailsTitle: 'Chapters',
    bookOverviewTitle: 'Book Details',
    bookMetaFormTitle: 'Book Metadata',
    editorTitle: 'Editor',
    statsTitle: 'Statistics',
    infoTitle: 'Help',
    settingsTitle: 'Settings',
  },
  info: {
    heading: 'Help and Guide',
    authorSection: 'Author',
    authorName: 'Kovzun V.A.',
    groupNumber: 'Group: IPZs-24-1',
    specialty: 'Specialty: Software Engineering',
    instructionSection: 'User Guide',
    instruction1: '1. Create a new book in Library by tapping "New Book"',
    instruction2: '2. Add chapters to your book',
    instruction3: '3. Edit chapter text in Editor with autosave',
    instruction4: '4. View statistics and export your work',
    themeSection: 'Color Scheme',
    themeJustification: 'Pastel tones are used to reduce eye strain during long writing sessions. Both light and dark themes are available.',
  },
  settings: {
    heading: 'Settings',
    themeLabel: 'Theme',
    darkTheme: 'Dark',
    lightTheme: 'Light',
    languageLabel: 'Language',
    langUkrainian: 'Ukrainian',
    langEnglish: 'English',
    langGerman: 'German',
  },
  menu: {
    about: 'Help',
    changeTheme: 'Settings',
    more: 'More',
  },
  toast: {
    quickHelp: 'Select text for formatting and use toolbar actions',
    themeSwitched: 'Theme switched',
    languageSwitched: 'Language switched',
    saved: 'Saved',
    error: 'Operation failed',
  },
  alerts: {
    info: 'Information',
    confirmation: 'Confirmation',
    selection: 'Choose',
    deleteChapter: 'Delete chapter?',
    deleteChapterMessage: 'Are you sure you want to delete this chapter? This action cannot be undone.',
    exportFormat: 'Select export format',
    exportFormatMessage: 'Choose export format.',
    exportTxt: 'TXT',
    exportDocx: 'DOCX',
    saveConfirm: 'Chapter saved successfully',
  },
  library: {
    heading: 'My Books',
    searchPlaceholder: 'Search by title',
    addBook: 'New Book',
    emptyState: 'Create your first book to start writing.',
    noSearchResults: 'No books found for your search.',
    progress: 'Progress',
    chapters: 'Chapters',
    addBookError: 'Failed to add book.',
    deleteBookConfirm: 'Delete book?',
    deleteBookMessage: 'This action cannot be undone.',
  },
  bookMeta: {
    createHeading: 'Create Book',
    editHeading: 'Edit Book',
    titleLabel: 'Title',
    titlePlaceholder: 'Enter book title',
    descriptionLabel: 'Annotation',
    descriptionPlaceholder: 'Write a short annotation',
    genreLabel: 'Genre',
    genrePlaceholder: 'Example: Fantasy, Drama',
    pickCover: 'Choose cover image',
    changeCover: 'Change cover image',
      deleteCoverTitle: 'Delete cover?',
      deleteCoverMessage: 'Are you sure you want to delete the cover image?',
    validationTitleRequired: 'Book title is required.',
    saveError: 'Failed to save book.',
  },
  bookDetails: {
    heading: 'Book Metadata',
    chaptersHeading: 'Book Chapters',
    openStats: 'Book Statistics',
    openChapters: 'Go to chapters',
    openEditor: 'Open editor',
    chaptersEmpty: 'No chapters yet.',
    addChapter: 'Add chapter',
    addChapterError: 'Failed to add chapter.',
    chapterPrefix: 'Chapter',
    editBook: 'Edit book',
    noDescription: 'No annotation added',
    noGenre: 'Genre is not set',
    noCover: 'No cover yet',
    deleteChapterConfirm: 'Delete chapter?',
  },
  bookStats: {
    totalWords: 'Total words',
    totalChars: 'Total characters',
    chaptersCount: 'Chapters',
    wordsPerChapter: 'Avg words/chapter',
    noChapters: 'No chapters yet',
    export: 'Export',
    exportAsText: 'Export as .txt',
    exportSuccess: 'Export successful',
    exportError: 'Export error',
  },
  editor: {
    heading: 'Chapter Text',
    placeholder: 'Start writing here...',
    searchPlaceholder: 'Type text to search',
    searchNoMatch: 'No matches found.',
    focusMode: 'Focus mode',
    focusModeOn: 'Focus mode enabled',
    focusModeOff: 'Focus mode disabled',
    autosaveSaving: 'Saving...',
    autosaveSaved: 'Saved',
    autosaveError: 'Save error',
    renameChapter: 'Rename chapter',
    deleteChapter: 'Delete chapter',
    rotateScreen: 'Rotate screen',
    formatting: {
      bold: 'Bold',
      italic: 'Italic',
      strike: 'Strike',
      search: 'Search',
      focusMode: 'Focus',
      rotate: 'Rotate',
    },
  },
};
