export const uk = {
  common: {
    loading: 'Завантаження...',
    noData: 'Немає даних',
    words: 'Слова',
    chars: 'Символи',
    untitled: 'Без назви',
    save: 'Зберегти',
    cancel: 'Скасувати',
    delete: 'Видалити',
    edit: 'Редагувати',
    close: 'Закрити',
    confirm: 'Підтвердити',
    description: 'Опис',
    genre: 'Жанр',
    ok: 'Добре',
    yes: 'Так',
    no: 'Ні',
  },
  navigation: {
    libraryTitle: 'Бібліотека',
    bookDetailsTitle: 'Зміст',
    bookOverviewTitle: 'Деталі книги',
    bookMetaFormTitle: 'Метаінформація',
    editorTitle: 'Редактор',
    statsTitle: 'Статистика',
    infoTitle: 'Довідка',
    settingsTitle: 'Налаштування',
  },
  info: {
    heading: 'Довідка та інструкція',
    authorSection: 'Авторство',
    authorName: 'Ковзун В.А.',
    groupNumber: 'Група: ІПЗс-24-1',
    specialty: 'Спеціальність: Інженерія програмного забезпечення',
    instructionSection: 'Інструкція користувача',
    instruction1: '1. Створіть нову книгу у Бібліотеці, натиснувши "Нова книга"',
    instruction2: '2. Додавайте розділи до своєї книги',
    instruction3: '3. Редагуйте текст розділів у Редакторі з автоматичним збереженням',
    instruction4: '4. Переглядайте статистику та експортуйте свою книгу у зручному форматі',
    themeSection: 'Колірна схема',
    themeJustification: 'Обрано пастельні тони для зменшення навантаження на зір під час тривалого написання тексту. Доступна як світла, так і темна тема задля забезпечення зручності та відповідності вподобанням користувачів.',
  },
  settings: {
    heading: 'Налаштування',
    themeLabel: 'Тема',
    darkTheme: 'Темна',
    lightTheme: 'Світла',
    languageLabel: 'Мова',
    langUkrainian: 'Українська',
    langEnglish: 'English',
    langGerman: 'Deutsch',
  },
  menu: {
    about: 'Довідка',
    changeTheme: 'Налаштування',
    more: 'Ще',
  },
  toast: {
    quickHelp: 'Виділіть текст для форматування та використовуйте кнопки на панелі інструментів',
    themeSwitched: 'Тема змінена',
    languageSwitched: 'Мову змінено',
    saved: 'Збережено',
    error: 'Помилка операції',
  },
  alerts: {
    info: 'Інформація',
    confirmation: 'Підтвердження',
    selection: 'Виберіть',
    deleteChapter: 'Видалити розділ?',
    deleteChapterMessage: 'Ви дійсно хочете видалити цей розділ? Це не можна скасувати.',
    exportFormat: 'Виберіть формат експорту',
    exportFormatMessage: 'У якому форматі експортувати?',
    exportTxt: 'TXT',
    exportDocx: 'DOCX',
    saveConfirm: 'Розділ збережено успішно',
  },
  library: {
    heading: 'Мої книги',
    searchPlaceholder: 'Пошук за назвою',
    addBook: 'Нова книга',
    emptyState: 'Створіть першу книгу, щоб почати писати.',
    noSearchResults: 'За вашим запитом книг не знайдено.',
    progress: 'Прогрес',
    chapters: 'Розділи',
    addBookError: 'Не вдалося додати книгу.',
    deleteBookConfirm: 'Видалити книгу?',
    deleteBookMessage: 'Ця дія не може бути скасована.',
  },
  bookMeta: {
    createHeading: 'Створення книги',
    editHeading: 'Редагування книги',
    titleLabel: 'Назва',
    titlePlaceholder: 'Введіть назву книги',
    descriptionLabel: 'Анотація',
    descriptionPlaceholder: 'Введіть анотацію книги',
    genreLabel: 'Жанр',
    genrePlaceholder: 'Введіть жанр книги',
    pickCover: 'Вибрати обкладинку',
    changeCover: 'Змінити обкладинку',
      deleteCoverTitle: 'Видалити обкладинку?',
      deleteCoverMessage: 'Ви впевнені, що хочете видалити обкладинку?',
    validationTitleRequired: 'Назва книги є обов\'язковою.',
    saveError: 'Не вдалося зберегти книгу.',
  },
  bookDetails: {
    heading: 'Метаінформація книги',
    chaptersHeading: 'Розділи книги',
    openStats: 'Статистика книги',
    openChapters: 'Перейти до розділів',
    openEditor: 'Відкрити редактор',
    chaptersEmpty: 'Поки що немає розділів.',
    addChapter: 'Додати розділ',
    addChapterError: 'Не вдалося додати розділ.',
    chapterPrefix: 'Розділ',
    editBook: 'Редагувати книгу',
    noDescription: 'Анотацію не додано',
    noGenre: 'Жанр не вказано',
    noCover: 'Поки без обкладинки',
    deleteChapterConfirm: 'Видалити розділ?',
  },
  bookStats: {
    totalWords: 'Всього слів',
    totalChars: 'Всього символів',
    chaptersCount: 'Розділів',
    wordsPerChapter: 'Ср. слів/розділ',
    noChapters: 'Поки що немає розділів.',
    export: 'Експортувати',
    exportAsText: 'Експортувати як .txt',
    exportSuccess: 'Експортовано успішно',
    exportError: 'Помилка експорту',
  },
  editor: {
    heading: 'Текст розділу',
    placeholder: 'Почніть писати тут...',
    searchPlaceholder: 'Введіть текст для пошуку',
    searchNoMatch: 'Збігів не знайдено.',
    focusMode: 'Режим фокусу',
    focusModeOn: 'Режим фокусу увімкнено',
    focusModeOff: 'Режим фокусу вимкнено',
    autosaveSaving: 'Зберігається...',
    autosaveSaved: 'Збережено',
    autosaveError: 'Помилка збереження',
    renameChapter: 'Перейменувати розділ',
    deleteChapter: 'Видалити розділ',
    rotateScreen: 'Повернути екран',
    formatting: {
      bold: 'Жирний',
      italic: 'Курсив',
      strike: 'Закреслений',
      search: 'Пошук',
      focusMode: 'Фокус',
      rotate: 'Повернути',
    },
  },
};
